version: '3.7'

services:
  hello-world:
    container_name: hello-world-live
    build:
      context: .
      dockerfile: Dockerfile-live
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL="this is just an environment variable for testing."