version: '3.7'

services:
  hello-world:
    container_name: hello-world
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL="this is just an environment variable for testing."